name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        dcompiler: [dmd-latest, dmd-beta, ldc-latest, ldc-beta]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.dcompiler }}
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dcompiler }}
    - name: Build
      run: dub build
    - name: Run Tests
      run: dub test
